### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RobTillaart** [marianomd/acs712-esphome#2]
As you do not have a license on your repo, is it OK to add a link to your repo in the readme.md of the ACS712 library.
https://github.com/RobTillaart/ACS712

A small section named ESPhome or so with a link to your repo.

triggered by - https://github.com/RobTillaart/ACS712/issues/40

**Comment by marianomd** [comment]
Hello Rob, I just added the license, and of course you can.

Thanks for the great library.

**Comment by RobTillaart** [comment]
done. 
(not created a new release for it)
