### ISSUE TITLE
How to add attenuation?

### ISSUE THREAD

**Issue by kgalilio** [marianomd/acs712-esphome#4]
By default, the esp32 adc is capped at 1.1V. Trying to measure a higher value requires higher attenuation.
I know how to set the attenuation using adc platform in esphome, but how can I configure it in the custom component?

**Comment by marianomd** [comment]
You have to customize acs712_component.h.

Check this line:

```
 ACS712 *ACS = new ACS712(A0, 3.3, 1023, 66);
```

Change the pin if needed, as well as 3.3 to 1.1V.

You can also tune the mV per ampere of your setup (the value 66) and the max ADC value (1023).
